# Generated by Django 2.1.4 on 2018-12-20 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação')),
                ('tipo_despesa', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('ROUPA', 'Roupas'), ('REMEDIO', 'Remédio'), ('TRANSPORTE', 'Transporte'), ('EDUCACAO', 'Educação'), ('OUTROS', 'Outros')], max_length=100)),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO DE CREDITO', 'Cartão de Crédito'), ('CARTAO DE DEBITO', 'Cartão de Débito'), ('CARTAO CREDIARIO', 'Cartão Crediário'), ('CHEQUE', 'Cheque')], max_length=100)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('quitado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Despesa agendada',
                'verbose_name_plural': 'Despesas agendadas',
            },
        ),
    ]
