# Generated by Django 2.1.4 on 2019-01-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='quitado',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='tipo_despesa',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='vencimento',
        ),
        migrations.AddField(
            model_name='despesa',
            name='cliente',
            field=models.CharField(default='a', max_length=200, verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='fornecedor',
            field=models.CharField(default='a', max_length=200, verbose_name='fornecedor'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='produto',
            field=models.CharField(default='a', max_length=200, verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(default='a', max_length=200, verbose_name='descrição'),
        ),
    ]
