# Generated by Django 2.1.4 on 2019-02-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190129_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='cliente',
            new_name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='fornecedor',
        ),
    ]
