# Generated by Django 2.1.4 on 2019-02-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190201_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='dia_semana',
            field=models.CharField(max_length=200, verbose_name='dia'),
        ),
    ]
